import 'package:flutter/material.dart';

class LanguageCodes{
  
  static String ytmidschool = "https://www.youtube.com/watch?v=3qDnfdsjG70";
  static String ythighschool = "https://www.youtube.com/watch?v=LTGH1ZnZ_08";
  static String ytcollege = "https://www.youtube.com/watch?v=XAIUROWp1vU";
  static String ytinsturctor = "https://www.youtube.com/watch?v=esB6d5azGUc";
  static String ytjob = "https://www.youtube.com/watch?v=L4gEpPOhpAY";
  static String ythousewife = "https://www.youtube.com/watch?v=Z684BDjwTPw";
  static String ytretured = "https://www.youtube.com/watch?v=AofS0CL-ULA";


 static Map<String, String> launguage_codes = {'English': 'en', 'Hindi': 'hi', 'Marathi': 'mr', 'Punjabi': 'pa', 'Telugu': 'te', 'Tamil': 'ta'};
 
 static String middleSchoolh1 = "How to Prevent Zoom Fatigue for Students Enrolled in Online Learning Classes";
 static String middleSchoolh2 = "Why ‘Zoom Fatigue’ Happens";
 static String middleSchoolText1 = "As schools and unversities around the world grow accustomed to remote learning, people have had to find the new ways to communicate and collaborate with students and fellow educators. Naturally, the most popular tools to emerge are video conferencing platforms. Zoom, Google Meet, Skype are the most popular platforms being used by educators.";
 static String middleSchoolText2 = "While these make it easy and efficient to conduct live video meetings from home, an increasing number of educators and their students express what they term ‘Zoom fatigue.’ It’s a new term being applied to the sense of boredom and tiredness people feel from attending numerous live meetings throughout the day.Here are the reasons why fatigue happens, ways to combat it.";
 static String middleSchoolText3 = "It’s never easy to stay focussed on live video calls. To understand your students, let’s check out why this happens. ";
 static String middleSchoolText4 = "Distractions – It can be hard to focus on live video meetings with distractions going on in the background. From siblings, pets, or parents, there are a number of things to distract a student at home.";
 static String middleSchoolText5 = "Physical Tiredness – It can be exhausting watching live video calls all day. Even though they aren’t moving, they may feel physically tired or act ‘zoned’ out during live meetings.";
 static String middleSchoolText6 = "Numerous Meetings – A student’s schedule can get hectic, especially those in high school.  If a student has a number of classes with different teachers, then it’s likely they attend several live meetings in a day. Understand your students and know that some of them are sitting through more live meetings than usual.";

  static String highSchoolh1 = "High School Life, Challenge and Solutions";
  static String highSchoolText1 = "A key lesson learned during the pandemic is the important role teachers play in ensuring that learning continues. As schools reopen, a lot will depend on teachers to ensure that children will be able to continue their education in a safe and healthy environment; and make up for knowledge and skills that may have been lost. As a teacher, knowing the facts will not only protect yourself but also your students. Be aware of fake information and dangerous myths about COVID-19 circulating that are feeding fear and stigma. ";
  static String highSchoolText2 = "Understanding COVID-19, how it spreads and how we can protect ourselves and others is an important first step in establishing classroom procedures and protocols. Students need to understand what it is in order for them to follow the rules. Listen to their concerns and ideas and answer their questions in an age-appropriate manner. Discuss the different reactions they may experience and explain that these are normal reactions to an abnormal situation.";
  static String highSchoolh2 = "Physical distancing at schools";
  static String highSchoolText3 = "Maintain a distance of at least 1 metre between everyone present at school. Increase desk spacing (at least 1 metre between desks), stagger recesses/breaks and lunch breaks (if difficult, one alternative is to have lunch at desks). Limit the mixing of classes for school and after-school activities. For example, students in a class will stay in one classroom throughout the day, while teachers move between classrooms; or classes could use different entrances, if available, or establish an order for each class to enter and leave the building/classroom. Stagger the school day to vary the start and end times and avoid having all the students and teachers together at once. Discuss how to manage physical education and sports lessons.";
  static String highSchoolh3 = "Health and hand hygiene";
  static String hightSchoolText4 = "Teachers have a critical role to play in ensuring students understand the precautions they should take to protect themselves and others from COVID-19, and it is important you lead by example in the classroom. Handwashing is one of easiest, more cost efficient and effective way of combating the spread of germs and keeping students and staff healthy.";
  static String highSchoolh4 = "Mask wearing in schools";
  static String hightSchoolText5 = "If wearing fabric masks is recommended in your school, then make sure your students are familiar with when they should wear masks and any related school policies, such as how to dispose of used masks safely to avoid the risk of contaminated masks in classrooms and playgrounds. All efforts should be made to ensure the use of a mask does not interfere with learning. No children should be denied access to education because of mask wearing or the lack of a mask because of low resources or unavailability.";
  static String highSchoolh5 = "Cleaning and disinfecting";
  static String hightSchoolText6 = "Daily cleaning and disinfecting of surfaces and objects that are touched often, such as desks, countertops, doorknobs, computer keyboards, hands-on learning items, taps, phones and toys. Immediately clean surfaces and objects that are visibly soiled. If surfaces or objects are soiled with body fluids or blood, use gloves and other standard precautions to avoid coming into contact with the fluid. Remove the spill, and then clean and disinfect the surface.";

  static String collegeh1 = "College Life, Challenges and Solutions";
  static String collegeh2 = "Tips for home studying during the coronavirus pandemic";
  static String collegeText1 = "The panic over COVID-19 has all but taken over the academic calendar, putting a question mark on the dates of the all-India exams the dates of which had been announced much earlier. While the Ministry of Human Resources have postponed the Joint Entrance Examination (Main), engineering entrance tests for admission into the National Institutes of Technology, Indian Institutes of Information Technology and other colleges, that were supposed to take place in the first week of April, along with the status of other examinations like NEET, JEE (Advanced) and CLAT are still unclear.Even when the educational bodies have declared that the examinations have been postponed, there is no one to counsel the students on their suddenly halted preparation process.";
  static String collegeText2 = "With May will come a deluge of entrance tests for which a large section of the country’s student population has been preparing for more than a year. Now, however, their futures have been thrown into disarray. The panic over COVID-19 has all but taken over the academic calendar, putting a question mark on the dates of the all-India exams the dates of which had been announced much earlier. While the Ministry of Human Resources have postponed the Joint Entrance Examination (Main), engineering entrance tests for admission into the National Institutes of Technology, Indian Institutes of Information Technology and other colleges, that were supposed to take place in the first week of April, along with the status of other examinations like NEET, JEE (Advanced) and CLAT are still unclear. Even when the educational bodies have declared that the examinations have been postponed, there is no one to counsel the students on their suddenly halted preparation process. Public libraries, where students coming from a middle-class set-ups have always found rescue, are now closed.";
  static String collegeText3 = "Those who were staying in different cities for better performance and had planned only to return after writing the examinations, are retrieving fearing crackdown on their movement in the coming days as the community transmission might begin. Dishu, a NEET aspirant from Bharatpur district of Rajasthan shifted to Jaipur last year with her mother to take admission into a medical coaching institute here. It’s been a year since she began her preparation to sit for the exam this year in May. However, post the COVID-19 shutdown, she is under pressure to return home and continue with her studies there.";
  static String collegeText4 = "Carve out (and clean out) your study space : If you already have a desk in your bedroom, that’s a great start. Do a little Marie Kondo-ing to de-clutter the space and make room for your books, computer and any other study tools. Remove, during your chosen study time, anything unrelated to your test prep. If you don’t have a desk in your room (maybe you’re sharing counter or table space with others in your home), choose a dedicated area where you can study. Make sure it’s clean, clutter-free and generally quiet during your study time. Also, be sure to remove all of your study materials once you’re finished, so that the space may go back to its original purpose.";
  static String collegeText5 = "Communicate to others in your home that you will be studying : It’s crucial to let anyone else in your home know when you’ll be studying, whether it is a set time each day or a block of hours on certain days. This will give you quiet time to focus and hopefully ensure that you are not disturbed.";
  static String collegeText6 = "Tune out distractions : If you find that you need to tune out the noise being made by others around your home, prepare yourself with some headphones and your favorite studying music. Instrumental music—classical, jazz, lo-fi hip hop or synthwave, for example—is helpful as background music, cancelling out unwanted noise as well as providing a motivating soundtrack for studying. Experiment with different genres to see what works for you.";
  static String collegeText7 = "Focus : During your chosen study times, focus. The more focused and dedicated you are, the more effective your study time will be. If you go over your allotted time, great! Your hyper-focus helped you to study hard and prepare even more than you’d planned. If you’re finding it difficult to focus, take a short break to stretch, breathe or enjoy some refreshments.";

  static String instructorh1 = "Remote Learning Tips by Instructors, for Instructors";
  static String instructorh2 = "Could you walk us through a “day in the life” for you, as schools are shut down indefinitely?";
  static String instructorText1 = "All of the teachers mentioned the discomfort of being glued to the computers in their home office. Most were set up in their living room. Mike starts off his weekday mornings by preparing a lesson plan. After finishing, he uses a free web service to upload and assign the lesson to his students. In addition, Mike uses video conferencing software to check in with his students daily. Casey uses the same free web service in a similar fashion to distribute, collect, and grade his students’ assignments.";
  static String instructorh3 = "As a middle school/high school/college educator, how, if at all, are you currently using remote learning with your students?";
  static String instructorText2 = "Casey and Mike have both made extensive use of a free suite of cloud-based collaboration, computing, and productivity tools to manage class assignments. On the other hand, Amy uses a popular learning management system and online conferencing service provided for all California Community Colleges. All assignments and exams are completed using this LMS and an online homework platform. In addition, Amy schedules class meetings and hosts virtual office hours through video conferencing.";
  static String instructorh4 = "How can remote learning address students with disabilities or special needs?";
  static String instructorText3 = "Amy agrees that remote learning doesn’t fully address the human interaction that some students need to succeed – especially the immediate human feedback received on campus tutoring centers. Still, educational technology has its benefits. ";
  static String instructorh5 = "Which distance learning tools and platforms would you recommend to other teachers at your grade level?";
  static String instructorText4 = "Each of the teachers we interviewed was testing out different tools to find out what works best in their home office. Amy has found a well-known tablet with a smart pen and virtual whiteboard to be useful during her lectures. Along with these tools, she uses screen-sharing software to share her desktop with her students. Casey has been using distance learning tools to try to bridge the gap between students, teachers, counselors, and other school staff. He has utilized a free web service to distribute, collect, and grade assignments. But, Casey’s overall ability to deliver content, tailor it to his students, collect feedback and adjust lessons in real time, and accurately assess his students’ understanding has been enormously impacted. Similarly, Mike has been experimenting with a combination of cloud-based productivity tools, video conferencing, as well as mobile-app based instructional content platforms.";
  static String instructorh6 = "What lessons have you learned about teaching your students remotely?";
  static String instructorText5 = "Amy, Casey, and Mike all highlighted the importance of establishing a remote learning routine. This helps comfort students by providing a semblance of normalcy, according to Mike. Amy suggests that if a virtual class meets on-and-off, then students should set up their own study schedule, as if they were in a face-to-face class, for going through the lesson material and completing the work on time. This discipline helps students stay motivated and on track. Casey uses weekly journals to have his students reflect on their own technology use. Before this shelter in place, I think most kids would say that they’d be perfectly happy to sit at home on their phone all day, he noted. Now, they are realizing that their devices and technology are only poor substitutes for real social interaction, education, and network-building. He does this exercise to raise awareness about using technology to stay connected.";

  static String jobh1 = "Jobs, Challenges and Solutions";
  static String jobText1 = "As COVID-19 continues to impact the daily lives of millions of people around the world and in Australia, those of you looking for stable full time employment will be feeling the strain even more. What was already a demanding task has now become even more challenging, with hundreds of companies making workers redundant or standing them down and even shutting down operations completely. We don’t want you to feel disheartened, even though you would be forgiven for assuming that now is not a good time to be job-hunting, which is why we’ve pulled together some tips on how to stay motivated during job search phases, as well as positive and determined to emerge from the COVID-19 crisis with a better job you enjoy.";
  static String jobh2 = "Don’t panic – companies are still hiring";
  static String jobText2 = "Easy for us to say, right? Well, we know that not all industries or companies are looking to pause their recruitment drives. Quite the reverse in fact, as some sectors are more in need of available hands than ever before, try searching for a better job on Naukri.com";
  static String jobh3 = "Know your rights if you are made redundant";
  static String jobText3 = "As COVID-19 continues to impact the daily lives of millions of people around the world and in Australia, those of you looking for stable full time employment will be feeling the strain even more. What was already a demanding task has now become even more challenging, with hundreds of companies making workers redundant or standing them down and even shutting down operations completely. We don’t want you to feel disheartened, even though you would be forgiven for assuming that now is not a good time to be job-hunting, which is why we’ve pulled together some tips on how to stay motivated during job search phases, as well as positive and determined to emerge from the COVID-19 crisis with a better job you enjoy. If the COVID-19 crisis has left your employer with no option but to make you redundant, rather than standing down, it is vital that you know what you are entitled to. It is important to find out if you are able to claim JobSeeker benefits. Although the maximum will depend on your circumstances, the JobSeeker Payment will be paid every 2 weeks.";
  static String jobh4 = "Make your finances your top priority";
  static String jobText4 = "•	Review all your direct debits and cut what is not necessary – Do you really need all your subscriptions to Netflix, Stan, Foxtel, Disney+, Spotify? •	Take the time and review your insurances – with everyone being in lockdown, do you have car insurance which you are paying for nothing? •	If you are renting a property – ask for a rent relief from your landlord if you are in financial stress, most of the landlord would be compassionate in this difficult time. •	If you own a property but have been stood down or made redundant, you would also be entitled to a mortgage payment deferment, however, interest may still apply. •	Ask for help — There’s no shame in asking friends and family for a little support if you find yourself out of work suddenly. It doesn’t have to be a case of lending you cash, either, as maybe moving back home for a few months would take a huge burden off your shoulders?";

  static String housewifeh1 = "Housewives, Challenges and Solutions";
  static String housewifeText1 = "A homemaker’s work never ends. In between cleaning, cooking, mopping, taking care of the children, and sometimes care-giving for elders, her life is an endless whirl of chores to complete and things and people to take care of. Being a homemaker is a choice for some, and a necessity for many who do not have a support system to fall back upon.";
  static String housewifeText2 = "These homemakers, apart from taking on an additional workload of having a working spouse and children at home, also have the onus of keeping their families positive and in good health as we face uncertainty. They are also doing all they can to contribute their bit as society grapples with this pandemic. For instance, Puja Das, a homemaker from West Bengal’s South Dinajpur district, has been making masks and distributing them for free among the locals.  Others are helping the elderly in their communities by shopping for groceries and also providing them food.";
  static String housewifeText3 = "How are they dealing with the additional responsibilities of having their families at home all day? Of making endless cups of chai for a spouse on con call and keeping their children entertained and busy.  It’s important to stay positive “Positivity goes a long way. My husband, who never misses a single day of office, even on weekends, is now restless cooped up at home. Thankfully, he takes over some of the household chores, while cribbing that I should have done better. After 30 years of marriage, I simply laugh it off and he joins in after he’s done complaining,” says Karuna, 52, a homemaker from Mumbai.";
  static String housewifeText4 = "Thankfully, both my children are adults and while things are messy around the house, it’s nice to hear their chatter. Of course, the work is more, as I have to clean up after their cooking experiments, but I don’t mind. My daughter and I pray together in the evenings and my son and I discuss movies. It’s all good so far, she adds. Samyuktha and her family Samyuktha, from Kochi, believes it’s a testing time for all of us, all over the world. It’s important to stay positive and that keeps anxiety at bay. We stay in the naval area and there is a lot of security around, and we make sure to maintain social distancing. My husband who is at home helps me out with the household chores. I also make sure to factor in a little bit of exercise during the day, she says. DebjaniSom from North Bengal feels nothing much has changed since the lockdown.  The routine is pretty much the same for me. But since the lockdown, although I do not go out that often, I feel a bit irritated and stuck. Normally, after lunch during the day, my husband would be outside for work, but since both of us are both home at all times, it kind of irritates me. I like being by myself and my husband likes digging old stuff around the house. There is no extra workload as such. I like doing the dishes; the housework keeps me occupied and helps the clock move faster, she says. Nisha Charles from Chennai believes her workload has reduced and she’s happy to be in a peaceful environment.";
  static String housewifeText5 = "Keeping anxiety at bay Not all homemakers have it easy. Some are riddled with anxiety, unsure of what the future holds for them and their families. In this time, it’s important that they take care of themselves, emphasises Meghna Prabhu, psychotherapist at Nowandme.com, a community-based platform that helps people talk about their mental health struggles and find comfort in knowing that they are not alone. Meghna lists some important tips for homemakers during these trying times. It’s important at this time to ask family members for help and support. If the other family members are healthy and fit, try to divide chores. Get the husband to help with teaching the kids, or washing clothes, washing dishes, sweeping, mopping, or even cooking. Divide chores. Children can help with cutting vegetables or washing dishes. If your child is young they can do fun supervised activities like watering the garden, plucking spinach leaves from stems, etc. This is a time to do things together.";
  
  static String retiredh1 = "Retired People, Challenges and Soluntions";
  static String retiredText1 = "The coronavirus disease (COVID-19) pandemic has brought about unprecedented fear and uncertainty, especially among older adults. The elderly rely on social connection more than most and they need it now more than ever. The elderly and retired sometimes need a helping hand and they also often need to have people around them. With India practicing a nation-wide lock down and social distancing vulnerable seniors could be feeling more alone than usual.";
  static String retiredText2 = "There are several reasons why the elderly are somewhat more vulnerable - they have more chronic conditions than younger people, their aging immune system makes it harder to fight off diseases, infections and viruses. Recoveries are usually slower and more complicated. Most of us are worried for our loved ones that are older and living far away from us. They might face anxiety because they live alone, are on a fixed income or pension, no longer drive and cannot take public transport, their routine health checkups are delayed. They could also have un-diagnosed or poorly managed depression. For millions of elderly COVID-19 has amplified their already-existing worries";
  static String retiredh2 = "Social Support";
  static String retiredText3 = "•	Check in on them regularly through phone calls. •	Send them a message or Whatsapp. •	Leave a note on their front door. Just to let them know someone is thinking about them. •	Cook something for them and leave it outside their door – ring the bell or let them know in advance that you are delivering a home cooked meal for them. Remember: always give it in a disposable container, sanitize the outside of the container by wiping with disinfectant. ";
  static String retiredh3 = "Run Errands";
  static String retiredText4 = "•	Buy them daily essentials like milk, bread, eggs, vegetables, fruit etc. •	Run to the grocery shop. •	Ensure their medical supplies are stocked up. •	Send them a little reminder asking them if they took their medication? ";
  static String retiredh4 = "Practice social distancing but not social isolation";
  static String retiredText5 = "•	Limit in-person visits. •	Help them understand the need to practice social distancing to keep them safe. •	It is tough for older adults who cherish the time spent with friends and family members to  maintain social distancing, so reassure them that you aren’t going anywhere.";
  static String retiredh5 = "Help them stay connected, feel involved, purposeful and less lonely";
  static String retiredText6 = "•	Show them how to video chat with others using smartphones, laptops or tablets. •	Encourage them to telephone their friends and family and to write kind notes to lift everyone's spirits.";
  static String retiredh6 = "Postpone unnecessary medical visits";
  static String retiredText7 = "•	Help them stay in touch with their doctors if they offer tele-medicine. •	As much as possible doctors and patients should communicate over video, email or other means rather than face-to-face.";
  static String retiredh7 = "Set up emergency contacts and speed dials";
  static String retiredText8 = "•	Identify one person nearby who they could rely on to care for them in case you are not available or far away. •	Help them to put all important phone numbers in speed dial. •	Add the COVID-19 emergency helpline numbers to their contacts and speed dial.";

  

}