import 'package:flutter/material.dart';

class LanguageCodes{
  
  static String ytmidschool = "https://www.youtube.com/watch?v=3qDnfdsjG70";
  static String ythighschool = "https://www.youtube.com/watch?v=JWTH94R3h40";
  static String ytcollege = "https://www.youtube.com/watch?v=eanFkZDWMns";
  static String ytinsturctor = "https://www.youtube.com/watch?v=esB6d5azGUc";
  static String ytjob = "https://www.youtube.com/watch?v=L4gEpPOhpAY";
  static String ythousewife = "https://www.youtube.com/watch?v=Z684BDjwTPw";
  static String ytretured = "https://www.youtube.com/watch?v=AofS0CL-ULA";


 static Map<String, String> launguage_codes = {'English': 'en', 'Hindi': 'hi', 'Marathi': 'mr', 'Punjabi': 'pa', 'Telugu': 'te', 'Tamil': 'ta'};
 
 static String middleSchooldc = "Data Analytics Observation - We carried out data analysis where we collected data from people in school from which we observed that most school kids attending online classes happen to exhaust while continuously on gadgets. The content below is derived by our data analysis.";
 static String middleSchoolh1 = "How to Prevent Zoom Fatigue for Students Enrolled in Online Learning Classes";
 static String middleSchoolh2 = "Why ‘Zoom Fatigue’ Happens";
 static String middleSchoolText1 = "As schools and unversities around the world grow accustomed to remote learning, people have had to find the new ways to communicate and collaborate with students and fellow educators. Naturally, the most popular tools to emerge are video conferencing platforms. Zoom, Google Meet, Skype are the most popular platforms being used by educators.";
 static String middleSchoolText2 = "While these make it easy and efficient to conduct live video meetings from home, an increasing number of educators and their students express what they term ‘Zoom fatigue.’ It’s a new term being applied to the sense of boredom and tiredness people feel from attending numerous live meetings throughout the day.Here are the reasons why fatigue happens, ways to combat it.";
 static String middleSchoolText3 = "It’s never easy to stay focussed on live video calls. To understand your students, let’s check out why this happens. ";
 static String middleSchoolText4 = "Distractions – It can be hard to focus on live video meetings with distractions going on in the background. From siblings, pets, or parents, there are a number of things to distract a student at home.";
 static String middleSchoolText5 = "Physical Tiredness – It can be exhausting watching live video calls all day. Even though they aren’t moving, they may feel physically tired or act ‘zoned’ out during live meetings.";
 static String middleSchoolText6 = "Numerous Meetings – A student’s schedule can get hectic, especially those in high school.  If a student has a number of classes with different teachers, then it’s likely they attend several live meetings in a day. Understand your students and know that some of them are sitting through more live meetings than usual.";
 static String middleSchoolh3 = "Tips to Prevent Zoom Fatigue for Students";
 static String middleSchoolText7 = "Due to our current circumstances, it might be quite difficult or impossible for you to meet up with coworkers or meet up with loved ones. To rectify the inability to engage in face-to-face interactions, many people are relying on webcam meetings or family webcam hangouts to fill these gaps. While often more convenient, this kind of social interaction can be mentally tiring so it's important to alleviate stress—which you can do with the following tips.Ground Yourself Before Video Conferencing Meetings. Grounding techniques can rely on any of your senses to connect you to the present moment and can be helpful when navigating draining interactions.";
 static String middleSchoolh4 = "Some examples of how you may do this include:";
 static String middleSchoolText8 = "1. Moisturizing your hands \n2. Naming the items in your workspace aloud \n3. Breathing in essential oils \n4. Massaging your temples";
 static String middleSchoolh5 = "Take Brief Breaks";
 static String middleSchoolText9 = "Given how exhausting it can be to invest in the cognitive demands of video conferencing communication, folx would benefit from scheduling in short breaks for themselves. When folx were used to regularly attending meetings in person, they would usually have to move from one location to another, which would provide some free time in between meetings. So, short breaks should also be built into remote working arrangements. You may also benefit from getting up and stretching and practicing deep breathing before and after video conferencing calls. So, it can be helpful for meetings to be scheduled for less time to allow for those much needed cognitive breaks.";
 static String middleSchoolh6 = "Find Connection Otherwise";
 static String middleSchoolText10 = "In a 2014 research study, it was demonstrated that even delays of 1.2 seconds on technological systems made folx perceive that the responder was less friendly or not as focused on communication with them. So, when speaking to others remotely, remind yourself that there is lag time and that the other person is likely not being rude or unfriendly on purpose. Also, during this time, you may need to focus on your connections with those in your home or with yourself to meet your needs for validation and connection.";
 static String middleSchoolh7 = "Consider If Video Conferencing Is Needed";
 static String middleSchoolText11 = "With most meetings occurring remotely, video conferencing communication has come to be the norm despite the increased cognitive demands of this process. Given how much more draining it can be, it is worth asking if video conferencing is necessary for the communication. If it's not, it might be a good idea to have the conversation over the phone or via email. These substitutions can help limit stress during your work day.";
 static String middleSchoolh8 = "Advocate For Yourself When You Feel Fatigued";
 static String middleSchoolText12 = "When you are stressed or tired, you might need to let your team know that you need a break or a mental health day. Setting boundaries, or letting people know where your needs and limits are, can often be stressful at first but will be well worth it.";

  static String highSchooldc = "Data Analytics Observation -We carried out data analysis where we collected data from people in Higher Education Institutes from which we observed that most higher education students are disturbed about competitive exams happening duringpandemic.";
  static String highSchoolh1 = "Higher Education Life, Challenges and Solutions";
  static String highSchoolText1 = "Higher education has offered distance instruction as an option for decades. Now that the pandemic of COVID-19 has reached every state in the U.S., many colleges have suddenly shifted to a forced kind of distance education—to keep teaching while everyone stays at least six feet apart to avoid spreading the virus. ";
  static String highSchoolText2 = "You may already know what knowledge or skills you’re after, but if not, spend some time thinking about your goals. Most well-designed learning experiences will come out and state their intended learning objectives – essentially the knowledge and skills you’re meant to get out of the experience. You certainly don’t want to waste your time, so make sure the experience is aimed at moving you toward your learning goals. Earning a professional certification to advance in your current job. Many organizations provide free learning resources on a variety of topics to their employees to encourage professional development, so it is worth looking into what your organization already has, and whether it meets your learning needs. Finally, once you’ve decided on a learning experience, it’s important to set yourself up for success with good habits and make efforts to keep yourself motivated.";
  static String highSchoolh2 = "Being proactive, present, and purposeful as an online student";
  static String highSchoolText3 = "You may not be able to raise your hand to ask questions like you did when you were in a physical classroom, but in your new online world, you’ll still have many digital resources to stay ahead of the game. Make sure you’re utilizing them. Pay attention to when live lectures are offered. If they’re optional, still do your best to attend them — it will help you feel like you never left your physical classroom. Take your work seriously — you may not be in a physical classroom, but you should act as if you are when you begin every study session. It’s up to you to take responsibility for your work and to appreciate the knowledge being given to you! ";
  static String highSchoolh3 = "Staying healthy — body and mind — during a crisis";
  static String hightSchoolText4 = "As a Physiological Science major and Global Health minor, UCLA junior Patricia Macalalag has a unique perspective on the worries of students and faculty in such a densely populated campus and city. Hear her thoughts on the rapid changes to teaching and learning, and how her areas of study shape her concerns during this current upheaval in education and society.";
  static String highSchoolh4 = "Being an introvert in the online world";
  static String hightSchoolText5 = "With so many students transitioning from campus education to online education, I’m reminded of my own experience. Shortly after finishing an in-person undergraduate program I entered my career and realized that the only way to pursue a master’s degree would be to complete it fully online. With a classroom full of peers staring me down, I was too shy to raise my hand and engage with the lecture. In the rare instance where I wanted to, my extroverted classmates sucked up the energy and left no time for the timid. When I did manage to be brave, whatever brilliant thought I had seemed to always come out as blubbering nonsense when spoken aloud. Another great thing about distance learning is flexibility. Gone are the days of set class times, juggling life around a Tetris-like schedule, and waking up before dawn to avoid a fight over decent parking. In online education, there’s an increased hesitancy for students to set appointments with their instructor. This is something I noticed from personal experience and something I’ve struggled with as an introvert all my life. It’s not that I don’t value having a substantial conversation with faculty; it’s that I get nervous asking for one-on-one support.";
  static String hightSchoolText6 = "1. Carve out (and clean out) your study space : \nIf you already have a desk in your bedroom, that’s a great start. Do a little Marie Kondo-ing to de-clutter the space and make room for your books, computer and any other study tools. Remove, during your chosen study time, anything unrelated to your test prep. If you don’t have a desk in your room (maybe you’re sharing counter or table space with others in your home), choose a dedicated area where you can study. Make sure it’s clean, clutter-free and generally quiet during your study time. Also, be sure to remove all of your study materials once you’re finished, so that the space may go back to its original purpose.";
  static String hightSchoolText7 = "2. Communicate to others in your home that you will be studying : \nIt’s crucial to let anyone else in your home know when you’ll be studying, whether it is a set time each day or a block of hours on certain days. This will give you quiet time to focus and hopefully ensure that you are not disturbed.";
  static String hightSchoolText8 = "3. Tune out distractions : \nIf you find that you need to tune out the noise being made by others around your home, prepare yourself with some headphones and your favorite studying music. Instrumental music—classical, jazz, lo-fi hip hop or synthwave, for example—is helpful as background music, cancelling out unwanted noise as well as providing a motivating soundtrack for studying. Experiment with different genres to see what works for you.";
  static String hightSchoolText9 = "4. Focus : \nDuring your chosen study times, focus. The more focused and dedicated you are, the more effective your study time will be. If you go over your allotted time, great! Your hyper-focus helped you to study hard and prepare even more than you’d planned. If you’re finding it difficult to focus, take a short break to stretch, breathe or enjoy some refreshments.";
  static String hightSchoolText10 = "5. Reward Yourself : \nFocusing on studying during a pandemic, especially under quarantine or shelter-in-place orders, comes with particular difficulties. If you’ve managed to study and focus for the duration of your goal time, be sure to reward yourself! The reward could be an extra hour of binge-watching your favorite show, eating an indulgent dessert, taking a nap or anything else that you enjoy. This will reinforce good study habits and, of course, it will be a well-deserved treat.";
  static String hightSchoolText11 = "6. Keep reading : \nWhether you’re reading for pleasure or for reference, keep at it. Reading has been proven to help with vocabulary, grammar and comprehension on standardised tests. It will also help to stimulate your mind in your downtime.";
  static String hightSchoolText12 = "7. Set Realistic Goals : \nWhen coming up with your study plan, be sure to set goals that you can actually achieve. If you plan to study for three hours a day while perhaps also juggling a full-time job that you’re now trying to do from home, you may fall short and lose motivation. Read some of our study and time management tips to help determine a manageable study schedule.";
  static String hightSchoolText13 = "Aishi Sharma, \nA student who has taken a drop year to prepare for engineering entrances said about online coaching classes, I took a drop believing that soon this pandemic will be over and I’ll be able to go back to my coaching classes where they will be able to provide me with the best trainings for my upcoming examinations. But now that dream seems like a faraway reality. I have online classes the entire day. It’s very tiring and every night my head throbs like anything. I am not able to participate much since my connectivity isn’t that great. On top of that, I find it really hard to concentrate on a single voice for that long, especially when the teacher is explaining formulas. Learning mathematical theorems online is such a pain! Both my eyesight and my mind have increasingly been losing focus with each passing day.";
  static String hightSchoolText14 = "Shreya, \nA second-year student from St. Xavier’s Kolkata shared: My eyes are exhausted every single day after my zoom classes. I have started using eye drops before bed in order to relax them at night as well as to get ready for the next day.";
  static String hightSchoolText15 = "Aditi Rai, \nAn undergraduate student from Jamia Millia Islamia in Delhi feels similarly, It\’s exhausting having to pay attention in an online class, and sometimes I have to force myself to concentrate, which is a struggle. I have also developed acute back pain since I am sitting in front of my laptop for 4-6 hours straight. She added, Five months in, I am still facing trouble adapting to this new system.";



  static String collegedc = "Data Analytics Observation –We carried out data analysis where we collected data from people in college from which we observed that most college students are much relaxed as they study from home.";
  static String collegeh1 = "College Life, Challenges and Solutions";
  static String collegeh2 = "How To Spend Time at Home During Lockdown?";
  static String collegeText1 = "Every dark cloud has a silver lining. Yes, that is true even in the case of the ongoing coronavirus induced lockdown. As social beings, it is difficult for all of us to stay at home all the time, however, we can still make the best of this time by indulging ourselves in some essential and fun activities. Although not everyone can perform everything recommended as a lot of activities depend on various factors such as age, health, and so on. Therefore, we have come up with different ideas that you can easily pick amid this lockdown period due to Coronavirus. All these activities require no financial investment or need to step outside, hence, anyone and everyone can opt for these without any hassle.";
  static String collegeText2 = "You can do these alone, with your family at home or even with your friends on call. Apart from keeping you mentally fit, the activities could bring the best out of you or can make something evolve that you can not think of as of now.";
  static String collegeText3 = "Let’s Explore Simple Ways To Spend Your Free Time During Corona Virus (COVID-19) Lockdown";
  static String collegeh3 = "1.	Work on Your Fitness Regime ";
  static String collegeText31 = "There is nothing more precious and rewarding than a healthy and fit body. You can use this extra time given to us by the lockdown to work on your fitness regime. Being fit does not only mean exercising, but it also includes maintaining peace of mind via meditation and yoga.";
  static String collegeText32 = "It is probably the best time you can indulge in doing exercise and ensuring that you remain healthy and fit. You can either start a new form of exercise or continue with your old workout routine. All that matters is that you exercise daily or at least 4 times a week.";
  static String collegeh4 = "2. Meditate at Home During Lockdown";
  static String collegeText41 = "If you want to experience mental peace, put on some music, and give meditation a try. Meditation will also help you reduce stress, increase energy, enhance the immune system, and benefit in a lot more ways.";
  static String collegeh5 = "3.	Cook and Eat Healthy Food at Home During Lockdown";
  static String collegeText51 = "You can also utilize this extra time to hone your cooking skills. If you do not know how to cook, begin with the easiest of recipes. If you already know how to cook, try dishes of other cuisines or try baking. The world of cooking is really huge. You can use this lockdown time to the best by exploring new dishes and new cooking styles.";
  static String collegeh6 = "4.	Dance Your Heart Out";
  static String collegeText61 = "Whether or not you are a fan of dancing, give it a try. You can also learn a new form of dance. It will not only enhance your mood, health, and fitness but also help you increase your confidence.";
  static String collegeh7 = "5.	Spend Some “Me Time”";
  static String collegeText71 = "Spend time with yourself. Yes, you read it right. In our busy lives, we often take out time for almost all important things and people except for ourselves. So, give yourself the much required ‘me time’. It could be anything, listening to good music, painting, or gardening.";
  static String collegeh8 = "6.	Play Games at Home During Lockdown";
  static String collegeText81 = "You can dedicate a specific time slot each day to play games such as hide and seek, charades, board games, Jenga, and numerous others with your entire family. Go and live your old childhood days.";
  static String collegeh9 = "7.	Watch Movies at Home During Lockdown";
  static String collegeText91 = "This is the idle time you can indulge in binge-watching old or new movies that you have never seen before. Pick a few good Hollywood or Bollywood movies, grab some popcorn, and call your family members to engage in this fun activity.";
  static String collegeh10 = "8. Create Music";
  static String collegeText101 = "Adults, as well as kids, love to try their hand at music. If you or your family have an interest in music, gather all your musical equipment in one place and start your musical experiments.";



  static String instructordc = "Data Analytics Observation - We carried out data analysis where we collected data from instructors from which we observed that most educators are finding stressful to teach from home."; 
  static String instructorh1 = "Remote Learning Tips by Instructors, for Instructors";
  static String instructorh2 = "Could you walk us through a “day in the life” for you, as schools are shut down indefinitely?";
  static String instructorText1 = "All of the teachers mentioned the discomfort of being glued to the computers in their home office. Most were set up in their living room. Mike starts off his weekday mornings by preparing a lesson plan. After finishing, he uses a free web service to upload and assign the lesson to his students. In addition, Mike uses video conferencing software to check in with his students daily. Casey uses the same free web service in a similar fashion to distribute, collect, and grade his students’ assignments.";
  static String instructorh3 = "As a middle school/high school/college educator, how, if at all, are you currently using remote learning with your students?";
  static String instructorText2 = "Casey and Mike have both made extensive use of a free suite of cloud-based collaboration, computing, and productivity tools to manage class assignments. On the other hand, Amy uses a popular learning management system and online conferencing service provided for all California Community Colleges. All assignments and exams are completed using this LMS and an online homework platform. In addition, Amy schedules class meetings and hosts virtual office hours through video conferencing.";
  static String instructorh4 = "How can remote learning address students with disabilities or special needs?";
  static String instructorText3 = "Amy agrees that remote learning doesn’t fully address the human interaction that some students need to succeed – especially the immediate human feedback received on campus tutoring centers. Still, educational technology has its benefits. ";
  static String instructorh5 = "Which distance learning tools and platforms would you recommend to other teachers at your grade level?";
  static String instructorText4 = "Each of the teachers we interviewed was testing out different tools to find out what works best in their home office. Amy has found a well-known tablet with a smart pen and virtual whiteboard to be useful during her lectures. Along with these tools, she uses screen-sharing software to share her desktop with her students. Casey has been using distance learning tools to try to bridge the gap between students, teachers, counselors, and other school staff. He has utilized a free web service to distribute, collect, and grade assignments. But, Casey’s overall ability to deliver content, tailor it to his students, collect feedback and adjust lessons in real time, and accurately assess his students’ understanding has been enormously impacted. Similarly, Mike has been experimenting with a combination of cloud-based productivity tools, video conferencing, as well as mobile-app based instructional content platforms.";
  static String instructorh6 = "What lessons have you learned about teaching your students remotely?";
  static String instructorText5 = "Amy, Casey, and Mike all highlighted the importance of establishing a remote learning routine. This helps comfort students by providing a semblance of normalcy, according to Mike. Amy suggests that if a virtual class meets on-and-off, then students should set up their own study schedule, as if they were in a face-to-face class, for going through the lesson material and completing the work on time. This discipline helps students stay motivated and on track. Casey uses weekly journals to have his students reflect on their own technology use. Before this shelter in place, I think most kids would say that they’d be perfectly happy to sit at home on their phone all day, he noted. Now, they are realizing that their devices and technology are only poor substitutes for real social interaction, education, and network-building. He does this exercise to raise awareness about using technology to stay connected.";
  static String instructorh7 = "Establish your presence right away";
  static String instructorText6 = "Welcome your students to the learning community. Tell them something about yourself—your background, your interests, a book you're currently reading. Describe what the course is about and what you hope students will learn. Establishing a community early on will help students feel welcome.";
  static String instructorText7 = "Be available. \"High-touch is more important than high-tech\",says online teacher Joanna Dunlap, assistant director of teacher effectiveness at the University of Colorado\'s Center for Faculty Development, in an Educause video. She encourages her students to call her if they need immediate advice. \"If a student is in crisis or needs to brainstorm an idea,\" she says, \"I want to be efficient.\" She admits that using the phone is low-tech but argues that it doesn\'t matter—all tech, she says, can be useful for online courses. Scott Cooper, writing for the website eLearning Industry, recommends telling students when you\'ll be visible and available, but he also advises that you establish a way students can contact you outside of those hours. He also recommends engaging with your students through online posts, forums, or social media. It\'s easy to come across as absent online, but good communication helps students see that you value their engagement. ";
  static String instructorh8 = "Use online resources";
  static String instructorText8 = "There is a ton of material online, says Patrick Lowenthal, professor of instructional design at Boise State University, in the Educause video, and you can lean on those resources. He stresses that it's important to help kids understand how to determine which sources are valid and trustworthy—and which aren't.";
  static String instructorText9 = "Don't lecture. Dunlap says that as she's grown more experienced as an online teacher, she's grown more comfortable being a little playful and surprising students with a quick video clip or an anecdote. Plugging in a story, a picture, or a little humor can liven up your lesson, she says. Expecting the unexpected keeps kids engaged and appreciative of their teacher's efforts.";
  static String instructorh9 = "Make your assignments clear";
  static String instructorText10 = "Students can find accessing and understanding assignments and notes online confusing, so make it easy for them to know what they have to do each week, when the work is due, and how much it counts toward their final grade. Provide ongoing feedback. Feedback is important in every classroom, but when you're teaching online, it's another way to establish that personal connection with your students. Cooper says that offering constructive feedback regularly helps students quickly identify behaviors or skills they need to improve and also makes them feel like they're part of the learning community. Cooper also recommends creating an open forum or discussion board so that students can support and mentor each other.";
  static String instructorh10 = "Applying e-Learning Strategies to the Traditional Classroom";
  static String instructorText11 = "Teaching online has helped me develop new strategies for the traditional classroom. Nowadays, I try to avoid lectures and include stories, pictures, examples, and anecdotes to foster meaningful engagement with my students. I've also created a series of 20-minute training videos for teachers, each installment focusing on a particular strategy, such as how to check for student understanding, how to give clear directions, and how to handle a disruptive student.";
  static String instructorText12 = "The key to using online strategies in any classroom, Dunlap says, is to choose what you want to teach and then add the technology—not the other way around. Letting students know a little about yourself, using stories and anecdotes, and being clear about assignments aren't just good for online learners—students in traditional classrooms appreciate these things, too. Adopting these strategies will help you create a positive environment in your classroom—whether it's in person or virtual.";
  static String instructorh11 = "Engaging Students Is Key";
  static String instructorText13 = "As you get started with online teaching, just remember that the first and last thing you need to do is to keep your students engaged. Teaching online required me to rethink not only how I presented the course material but how I presented myself as a teacher. When teachers can't look at their students' faces or read their body language, it's tempting for them to focus only on the content and ignore whether students are engaging with the material.";

  
  static String jobdc = "Data Analytics Observation - We carried out data analysis where we collected data from people in Job from which we observed that most Employees (mainly concerned of IT industry) happen to fear of losing jobs.";
  static String jobh1 = "Jobs, Challenges and Solutions";
  static String jobText1 = "As COVID-19 continues to impact the daily lives of millions of people around the world and in Australia, those of you looking for stable full time employment will be feeling the strain even more. What was already a demanding task has now become even more challenging, with hundreds of companies making workers redundant or standing them down and even shutting down operations completely.";
  static String jobText11 = "We don’t want you to feel disheartened, even though you would be forgiven for assuming that now is not a good time to be job-hunting, which is why we’ve pulled together some tips on how to stay motivated during job search phases, as well as positive and determined to emerge from the COVID-19 crisis with a better job you enjoy.";
  static String jobh2 = "Don’t panic – companies are still hiring";
  static String jobText2 = "Easy for us to say, right? Well, we know that not all industries or companies are looking to pause their recruitment drives. Quite the reverse in fact, as some sectors are more in need of available hands than ever before, try searching for a better job on Naukri.com";
  static String jobh3 = "Know your rights if you are made redundant";
  static String jobText3 = "It is worth bearing in mind that as new restrictions on movement are being enforced, it is likely that some of the most recruitment-focused companies and industries will change. For example, fast food preparation and delivery outlets are unlikely to still be looking for people to fill positions now, but they may well be keen to get a full staffing contingent in place for when normal business resumes.";
  static String jobText31 = "If the COVID-19 crisis has left your employer with no option but to make you redundant, rather than standing down, it is vital that you know what you are entitled to. It is important to find out if you are able to claim JobSeeker benefits. Although the maximum will depend on your circumstances, the JobSeeker Payment will be paid every 2 weeks.";
  static String jobText32 = "If you are part of a lay-off initiative that sees you working fewer hours than normal, check your contract to make sure that your employer can make contractual changes of this magnitude and if you have agreed to be left unpaid for a number of hours each week.";
  static String jobText33 = "The Government is keen to help job seekers who have been made redundant to make a fast and efficient return to the employment world, and as such, have put together an online guide about bouncing back from the loss of a job. This covers everything from your mutual obligations.";
  static String jobh4 = "Make your finances your top priority";
  static String jobText4 = "1. Review all your direct debits and cut what is not necessary – Do you really need all your subscriptions to Netflix, Stan, Foxtel, Disney+, Spotify? \n2. Take the time and review your insurances – with everyone being in lockdown, do you have car insurance which you are paying for nothing? \n3.	If you are renting a property – ask for a rent relief from your landlord if you are in financial stress, most of the landlord would be compassionate in this difficult time. \n4.	If you own a property but have been stood down or made redundant, you would also be entitled to a mortgage payment deferment, however, interest may still apply. \n5.	Ask for help — There’s no shame in asking friends and family for a little support if you find yourself out of work suddenly. It doesn’t have to be a case of lending you cash, either, as maybe moving back home for a few months would take a huge burden off your shoulders?";


  static String housewifedc = "Data Analytics Observation - We carried out data analysis where we collected data from Housewives from which we observed that most housewives are physically exhausted which also affect their mental health due to increased workloadas mostly maids are not coming for work due to pandemic.";
  static String housewifeh1 = "Housewives, Challenges and Solutions";
  static String housewifeText1 = "A homemaker’s work never ends. In between cleaning, cooking, mopping, taking care of the children, and sometimes care-giving for elders, her life is an endless whirl of chores to complete and things and people to take care of. Being a homemaker is a choice for some, and a necessity for many who do not have a support system to fall back upon.";
  static String housewifeText2 = "Homemakers, apart from taking on an additional workload of having a working spouse and children at home, also have the onus of keeping their families positive and in good health as we face uncertainty. They are also doing all they can to contribute their bit as society grapples with this pandemic. For instance, Puja Das, a homemaker from West Bengal’s South Dinajpur district, has been making masks and distributing them for free among the locals.  Others are helping the elderly in their communities by shopping for groceries and also providing them food.";
  static String housewifeText3 = "How are they dealing with the additional responsibilities of having their families at home all day? Of making endless cups of chai for a spouse on con call and keeping their children entertained and busy.  It\’s important to stay positive \"Positivity goes a long way. My husband, who never misses a single day of office, even on weekends, is now restless cooped up at home. Thankfully, he takes over some of the household chores, while cribbing that I should have done better. After 30 years of marriage, I simply laugh it off and he joins in after he’s done complaining,\" says Karuna, 52, a homemaker from Mumbai";
  static String housewifeText4 = "\"Thankfully, both my children are adults and while things are messy around the house, it\’s nice to hear their chatter. Of course, the work is more, as I have to clean up after their cooking experiments, but I don\’t mind. My daughter and I pray together in the evenings and my son and I discuss movies. It\’s all good so far,\" she adds. Samyuktha and her family Samyuktha, from Kochi, believes it\’s a testing time for all of us, all over the world. It\’s important to stay positive and that keeps anxiety at bay. We stay in the naval area and there is a lot of security around, and we make sure to maintain social distancing. My husband who is at home helps me out with the household chores. I also make sure to factor in a little bit of exercise during the day,\" she says. DebjaniSom from North Bengal feels nothing much has changed since the lockdown.  \"The routine is pretty much the same for me. But since the lockdown, although I do not go out that often, I feel a bit irritated and stuck. Normally, after lunch during the day, my husband would be outside for work, but since both of us are both home at all times, it kind of irritates me. I like being by myself and my husband likes digging old stuff around the house. There is no extra workload as such. I like doing the dishes; the housework keeps me occupied and helps the clock move faster,\" she says. Nisha Charles from Chennai believes her workload has reduced and she\’s happy to be in a peaceful environment.";
  static String housewifeh2 = "Tips for Keeping anxiety at bay !";
  static String housewifeText5 = "Not all homemakers have it easy. Some are riddled with anxiety, unsure of what the future holds for them and their families. In this time, it’s important that they take care of themselves, emphasises Meghna Prabhu, psychotherapist at Nowandme.com, a community-based platform that helps people talk about their mental health struggles and find comfort in knowing that they are not alone.";
  static String housewifeText6 = "Meghna lists some important tips for homemakers during these trying times. It’s important at this time to ask family members for help and support. If the other family members are healthy and fit, try to divide chores. Get the husband to help with teaching the kids, or washing clothes, washing dishes, sweeping, mopping, or even cooking. Divide chores. Children can help with cutting vegetables or washing dishes. If your child is young they can do fun supervised activities like watering the garden, plucking spinach leaves from stems, etc. This is a time to do things together. If possible cook in bulk and freeze.";
  static String housewifeText7 = "Take time out to talk to friends and parents, have a group chat, ask them how they are managing and share your feelings. This type of peer therapy in some ways can be very useful.  If you have time, try yoga. It’s a good way to relax the body and mind. If you have less time, have a hot shower. The biggest challenge is keeping children occupied. One way is to give them chores. You can also encourage them to read. Give them activities and games that will keep them busy. If they have homework, ask your husband or the older sibling to help the younger one.";
  static String housewifeText8 = "Most importantly make sure to take care of yourself, boost your immunity, and get enough sleep. It’s a time for everyone to develop new skills and work together to come out of this stronger.  "; 
  

  static String retireddc = "Data Analytics Observation - We carried out data analysis where we collected data from Senior Citizens from which we observed that most senior citizens have mental stress because they fear of contracting coronavirus.";
  static String retiredh1 = "Senior Citizens, Challenges and Solutions";
  static String retiredText1 = "The coronavirus disease (COVID-19) pandemic has brought about unprecedented fear and uncertainty, especially among older adults. The elderly rely on social connection more than most and they need it now more than ever. The elderly and retired sometimes need a helping hand and they also often need to have people around them. With India practicing a nation-wide lock down and social distancing vulnerable seniors could be feeling more alone than usual.";
  static String retiredText2 = "There are several reasons why the elderly are somewhat more vulnerable - they have more chronic conditions than younger people, their aging immune system makes it harder to fight off diseases, infections and viruses. Recoveries are usually slower and more complicated.";
  static String retiredText12 = "Senior citizens might face anxiety because they live alone, are on a fixed income or pension, no longer drive and cannot take public transport, their routine health checkups are delayed. They could also have un-diagnosed or poorly managed depression. For millions of elderly COVID-19 has amplified their already-existing worries.";
  static String retiredh3 = "Run Errands";
  static String retiredText4 = "•	Ensure your medical supplies are stocked up. \n•	Set up reminder on phoneto take medication on time.";
  static String retiredh4 = "Practice social distancing but not social isolation";
  static String retiredText5 = "•	Limit your in-person visits. \n• Understand the need to practice social distancing to be safe.";
  static String retiredh5 = "Feel involved, purposeful and less lonely";
  static String retiredText6 = "•	Learn how to video chat with others using smartphones, laptops or tablets. \n•	Encourage yourself to telephone your friends and family and to write kind notes to lift everyone's spirits.";
  static String retiredh6 = "Postpone unnecessary medical visits";
  static String retiredText7 = "•	Try staying in touch with your doctors if they offer tele-medicine. \n•	As much as possible doctors and patients should communicate over video, email or other means rather than face-to-face.";
  static String retiredh7 = "Set up emergency contacts and speed dials";
  static String retiredText8 = "•	Identify one person nearby who you could rely on to care for you. \n•	Add the COVID-19 emergency helpline numbers to your contacts and speed dial.";


  

}