import 'package:flutter/material.dart';
import 'constants.dart';
import 'package:google_fonts/google_fonts.dart';

class Symptoms extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        centerTitle: true,
        title: Text('Symptoms',style:GoogleFonts.montserrat(fontWeight: FontWeight.bold),),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Container(
          child: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  SizedBox(height: 5,),
                  Text('COVID-19 affects different people in different ways. Most infected people will develop mild to moderate illness and recover without hospitalization.',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.justify,
                    style: (cTitle(Colors.black)),
                    maxLines:6,
                  ),
                  SizedBox(height: 5,),
                  Text('The most common symptoms of COVID-19 are:\n * Fever\n * Dry cough\n * Fatigue',
                    overflow: TextOverflow.ellipsis,
                    style: cTitle(Colors.black),
                    //textAlign: TextAlign.justify,
                    maxLines: 5,
                  ),
                  SizedBox(height: 5,),
                  Text('Less common symptoms:\n * Loss of taste or smell\n * Nasal congestion\n * Conjunctivitis\n * Sore throat\n * Headache\n * Muscle or joint pain\n * Different types of skin rash\n * Nausea or vomiting\n * Diarrhea\n * Chills or dizziness',
                    overflow: TextOverflow.ellipsis,
                    style: cTitle(Colors.black),
                    maxLines: 10,
                    //textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 5,),
                  Text('Severe symptoms:\n * Shortness of breath\n * Loss of appetite\n * Confusion\n * Persistent pain or pressure in the chest\n * High temperature(above 38°C)',
                    overflow: TextOverflow.ellipsis,
                    style: cTitle(Colors.black),
                    maxLines: 10,
                    //textAlign: TextAlign.justify,
                  ),
                  SizedBox(height: 5,),
                  Text('Other less common symptoms:\n * Irritability\n * Confusion\n * Reduced consciousness\n * Anxiety\n * Depression\n * Sleep disorders,\n * More severe and rare neurological complications such as strokes, brain inflammation, delirium and nerve damage.',
                    overflow: TextOverflow.ellipsis,
                    style: cTitle(Colors.black),
                    maxLines: 20,
                 //   textAlign: TextAlign.justify,
                  ),
                  SizedBox(height:5,),
                  Text('Seek immediate medical attention if you have serious symptoms. Always call before visiting your doctor or health facility.',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.justify,
                    style: cTitle(Colors.black),
                    maxLines:6,
                  ),
                  SizedBox(height: 5,),
                  Text('People with mild symptoms who are otherwise healthy should manage their symptoms at home.',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.justify,
                    style: cTitle(Colors.black),
                    maxLines:3,
                  ),
                  SizedBox(height: 5,),
                  Text('On average it takes 5-6 days from when someone is infected with the virus for symptoms to show, however it can take up to 14 days.',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.justify,
                    style: cTitle(Colors.black),
                    maxLines:6,
                  ),
                  SizedBox(height: 5,),
                  Text('STAY HOME STAY SAFE',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.center,
                    style: cTitle(Colors.red),
                  ),
                  SizedBox(height: 5,),
                  Text('Source: World Health Organization',
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.center,
                    style: cTitle(Colors.black26),
                  ),
                ],
              ),
          ),
        ),
      ),
    );
  }
}
